language: python
sudo: required
dist: trusty
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - 3.4
virtualenv:
  system_site_packages: true
script:
  - "python test_project/setup.py test"
install:
  - pip install pep8
