language: python
sudo: required
dist: trusty
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - 3.4
virtualenv:
  system_site_packages: true
script:
  - pep8 --ignore=E121,E123,E126,E226,E24,E704,E501 pyramid_jsonapi
  - python test_project/setup.py test
install:
  - pip install pep8
