language: python
sudo: required
dist: trusty
addons:
  postgresql: "9.6"
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - 3.4
virtualenv:
  system_site_packages: true
script:
  - pep8 --ignore=E501 pyramid_jsonapi
  - python test_project/setup.py test
  - travis-sphinx build
install:
  - pip install pep8
  - pip install travis-sphinx
after:
  - travis-sphinx deploy
