language: python
sudo: required
dist: trusty
addons:
  postgresql: '9.6'
cache:
- apt
- directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
- 3.4
virtualenv:
  system_site_packages: true
script:
- pep8 --ignore=E501,E731 pyramid_jsonapi
- pylint -E --rcfile=.pylintrc pyramid_jsonapi
- python test_project/setup.py test
install:
- pip install -r requirements.txt
- pip install pep8
- pip install pylint
- pip install sphinx
- pip install travis-sphinx
- python setup.py install
after_success:
- travis/sphinx.sh
deploy:
  provider: pypi
  user: "colinhiggs"
  on:
    branch: master
  password:
    secure: "YAq6KEOf4LnXgf9MkW0DRHLzxPGob5a6y/b38eQ/wD/KEL6rZjHvS92E1qEuTe+Et6RAoWz6e76j5ntQS9Qf7rJfIuxcqWl19ofXTmACcjHd6Evblqz8llGUlKTBKchkQ7yMm6tbkyYHLrUYgZPyr+0lB8G94wAh+qBd460kAMFEhPPOMCUDdtIA+jeU6dENFO9V/BFOBlOuoIEw6PLT96z
gQCvUMza3O2Op4hT7zsyI9U/7jXM1RgV6/HF3TcyQTpTFBMoOeSrASTt6tT4LF7Ws3HL1HIe/Gy0smBseDP45csqP90uiqUvfv8P0lv31tgTrn2e5tjbTHhKeeN3th+hxyzwn2ss1XoH8gvcVdiq7+AKg41WXUgceAXsQfWXf53JjpmRzSw/fj5YBJ3x16gnVtUbZmDE9TnGneAyrwN6QTk56q2SUmDIj5
ea+QCo3WnRcxHk0Ir0JUoBINW5HVoPlpT64eNmHftNiWSaDo7SaPfV1wIN9TbCJcm05IZtk3l8RiyWf/KQUGy3LRJRb1nZkq8dDPnPBcktWVRFjC55ibFEs6TtSXlX67PPVbNE8SU/bKOkzfcWiYT6bOXn9/t83LwoQj50sBq0052baI3l/fXQh8KfTCQflCsHQ8q4jU3mHIvbZSKzDQp3UNsi8cEM1CEw
wFpYNnan9SIyD5HU="
